# Generated by Django 4.2.15 on 2024-12-04 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ewiz_app', '0003_alter_jobopenings_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopenings',
            name='key_skills',
            field=models.TextField(blank=True, null=True),
        ),
    ]
