# Generated by Django 4.2.15 on 2024-12-04 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ewiz_app', '0004_jobopenings_key_skills'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobopenings',
            name='key_skills',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
