# Generated by Django 4.2.15 on 2024-12-06 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ewiz_app', '0005_alter_jobopenings_key_skills'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobopenings',
            name='Job_Openings',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
